language: node_js
sudo: false
env:
  global:
    - CXX=g++-4.8
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
node_js:
  - '8'
  - '9'
  - '10'
install:
  - npm install --global npm
  - npm install
