language: node_js
env:
  global:
    - CXX=g++-4.8
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
node_js:
  - '12'
install:
  - npm install
script:
  - npm test
  - ./bin/index.js --version
matrix:
  include:
    - os: osx
      osx_image: xcode10.2
    - os: windows
    - os: linux
